### PR TITLE
Adding build script

### PR DESCRIPTION
**Pull request by ckolos**
@jaredkerim r?

### CODE REVIEW

**Comment by jaredkerim** [comment]
Why are there two Docker files, one without the version json info?

**Comment by ckolos** [comment]
@jaredkerim Good question. 1 dockerfile is intended to be used with the ops script that would/will be called through our workflow on the backend. That script, as mentioned in the config, creates the version.json file outside the context of the docker build process so that we A) don't have a seperate slice in the resulting container and B) allows us to remove/elide .git in same. The additional/extra/original dockerfile is intended for use in workflows that are not "ours".

**Comment by jaredkerim** [comment]
@ckolos but the only difference between the two is the inclusion of the git json step.  I don't want to have two duplicate dockerfiles that are nearly identical, then when we have to make a change we have to change both.  Including the git json info blob is only useful for production deploys anyways, in which case Dockerfile.ops still behaves correctly for dev, testing, etc workflows.  We should just keep it as one Dockerfile and move the git json info to the build script as you've done here.

**Comment by ckolos** [comment]
wfm!

**Comment by jaredkerim** [comment]
R+!

**Pull request merged**
